<a href="https://colab.research.google.com/github/talhanoor23/algorithmic-trading/blob/main/pandasTA_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade pip
!pip uninstall -y numpy pandas_ta
!pip install numpy==1.24.3 pandas_ta

In [ ]:
!pip install yfinance pandas_datareader

In [ ]:
from statsmodels.regression.rolling import RollingOLS
import pandas as pd
import pandas_ta as ta
import yfinance as yf
import pandas_datareader.data as pdr
import matplotlib.pyplot as plt
import statsmodels.api as sm
import datetime as dt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# import pandas as pd
# import pandas_ta as ta
# import yfinance as yf
# import datetime as dt

# # Fetch data using yfinance
# ticker = "BTC-USD"
# start_date = "2023-01-01"
# end_date = "2024-01-01"

# df = yf.download(ticker, start=start_date, end=end_date)

# # Flatten MultiIndex columns
# df.columns = ['_'.join(col).strip() for col in df.columns.values]

# # Example: Add Simple Moving Average (SMA) manually
# df['SMA_14'] = df['Close_BTC-USD'].rolling(window=14).mean()

# # Display the first few rows to confirm data is loaded and indicators are added
# display(df.head())
# display(df.tail())

In [ ]:
# df = yf.download("BTC-USD", start="2023-01-01", end="2024-01-01")
df = yf.download("aapl")

[*********************100%***********************]  1 of 1 completed

In [ ]:
# df = pd.DataFrame()
# df = df.ta.ticker("BTC-USD")

In [ ]:
df

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
1980-12-12    0.098597    0.099025    0.098597    0.098597  469033600
1980-12-15    0.093453    0.093881    0.093453    0.093881  175884800
1980-12-16    0.086594    0.087022    0.086594    0.087022  105728000
1980-12-17    0.088737    0.089166    0.088737    0.088737   86441600
1980-12-18    0.091310    0.091738    0.091310    0.091310   73449600
...                ...         ...         ...         ...        ...
2025-06-10  202.669998  204.350006  200.570007  200.600006   54672600
2025-06-11  198.779999  204.500000  198.410004  203.500000   60989900
2025-06-12  199.199997  199.679993  197.360001  199.080002   43904600
2025-06-13  196.449997  200.369995  195.699997  199.729996   51447300
2025-06-16  198.419998  198.690002  196.559998  197.300003   42886800

[11218 rows x 5 columns]

In [ ]:
df.columns = ['_'.join(col).strip() for col in df.columns.to_flat_index()]
df.columns = df.columns.str.lower()

In [ ]:
df.ta.sma(length=14, append=True) #auto or efficient method.
# df.ta.ticker("aapl", period = "1mo", interval = "1h", append=True)
# df['SMA_14'] = df['Close_BTC-USD'].rolling(window=14).mean() #Manual mehtod.

In [ ]:
df

,close_aapl,high_aapl,low_aapl,open_aapl,volume_aapl,SMA_14
Date,,,,,,
1980-12-12,0.098597,0.099025,0.098597,0.098597,469033600,NaN
1980-12-15,0.093453,0.093881,0.093453,0.093881,175884800,NaN
1980-12-16,0.086594,0.087022,0.086594,0.087022,105728000,NaN
1980-12-17,0.088737,0.089166,0.088737,0.088737,86441600,NaN
1980-12-18,0.091310,0.091738,0.091310,0.091310,73449600,NaN
...,...,...,...,...,...,...
2025-06-10,202.669998,204.350006,200.570007,200.600006,54672600,201.186430
2025-06-11,198.779999,204.500000,198.410004,203.500000,60989900,200.950001
2025-06-12,199.199997,199.679993,197.360001,199.080002,43904600,200.795715
2025-06-13,196.449997,200.369995,195.699997,199.729996,51447300,200.880001
2025-06-16,198.419998,198.690002,196.559998,197.300003,42886800,200.752143

In [ ]:
help(df.ta.indicators())

In [ ]:
help(ta.aberration)

In [ ]:
rsi = ta.rsi(df['close_aapl'], length=14) #rsi is indicator and present in df.ta.indicators

In [ ]:
df['rsi'] = rsi

In [ ]:
df

,close_aapl,high_aapl,low_aapl,open_aapl,volume_aapl,SMA_14,rsi
Date,,,,,,,
1980-12-12,0.098597,0.099025,0.098597,0.098597,469033600,NaN,NaN
1980-12-15,0.093453,0.093881,0.093453,0.093881,175884800,NaN,NaN
1980-12-16,0.086594,0.087022,0.086594,0.087022,105728000,NaN,NaN
1980-12-17,0.088737,0.089166,0.088737,0.088737,86441600,NaN,NaN
1980-12-18,0.091310,0.091738,0.091310,0.091310,73449600,NaN,NaN
...,...,...,...,...,...,...,...
2025-06-10,202.669998,204.350006,200.570007,200.600006,54672600,201.186430,48.910651
2025-06-11,198.779999,204.500000,198.410004,203.500000,60989900,200.950001,43.656713
2025-06-12,199.199997,199.679993,197.360001,199.080002,43904600,200.795715,44.351762
2025-06-13,196.449997,200.369995,195.699997,199.729996,51447300,200.880001,40.802560
2025-06-16,198.419998,198.690002,196.559998,197.300003,42886800,200.752143,44.244670

In [ ]:
df['v_rsi'] = ta.rsi(df['volume_aapl'], length = 14)

In [ ]:
df

,close_aapl,high_aapl,low_aapl,open_aapl,volume_aapl,SMA_14,rsi,v_rsi
Date,,,,,,,,
1980-12-12,0.098597,0.099025,0.098597,0.098597,469033600,NaN,NaN,NaN
1980-12-15,0.093453,0.093881,0.093453,0.093881,175884800,NaN,NaN,NaN
1980-12-16,0.086594,0.087022,0.086594,0.087022,105728000,NaN,NaN,NaN
1980-12-17,0.088737,0.089166,0.088737,0.088737,86441600,NaN,NaN,NaN
1980-12-18,0.091310,0.091738,0.091310,0.091310,73449600,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2025-06-10,202.669998,204.350006,200.570007,200.600006,54672600,201.186430,48.910651,49.860213
2025-06-11,198.779999,204.500000,198.410004,203.500000,60989900,200.950001,43.656713,51.368071
2025-06-12,199.199997,199.679993,197.360001,199.080002,43904600,200.795715,44.351762,47.231107
2025-06-13,196.449997,200.369995,195.699997,199.729996,51447300,200.880001,40.802560,49.177081
2025-06-16,198.419998,198.690002,196.559998,197.300003,42886800,200.752143,44.244670,47.056122